### ISSUE TITLE
Feedback about persistent configuration for the ctl

### ISSUE THREAD

**Issue by gianarb** [cherryservers/cherryctl#1]
Hello!
I am using the `cherryctl` it is very easy but I find myself doing the same things over and over at the beginning:

```sh
cherryctl list tems
cherryctl list projects --team-id whatever
```

My suggestion is to code something that works similar to what the kubectl or the aws-cli do.
A configuration file where you can mask teams and project as context, switching between them.

```yaml
context:
  - name: default
    team-id: 34561
    project-id: 8563
  - name: default
    team-id: 34561
    project-id: 8563
current-context: default
```
The `project-id` can be optional as well. I don't know if there is the possibility to manage more accounts or the team scales enough. If you think there are people with multiple accounts we can have support for credentials as well.

```yaml
auth:
   - name: myaccount1
     auth-token: 34ys4h6d5e6yhrd56yhr65hr5h
   - name: myaccount2
     auth-token: 784t8ikt78kt78k78k87k
context:
  - name: default
    team-id: 34561
    project-id: 8563
    auth-name: myaccount1
  - name: juventus
    team-id: 34561
    project-id: 8563
    auth-name: myaccount1
current-context: default
```
This process makes very easy to remember team-id and project-id because they will get friendly names easy to recall.

```
cherryctl config use-context juventus
```
Changes the ctx context to juventus and from that point in time `--project-id` will be set automatically to 8563, same for the team-id where needed.

Thanks for your work

**Comment by ArturasRa** [comment]
Hi there, this is actually great idea, which might save time on recurring actions. I will sleep on that idea and leave this issue open until we have decision on the way how to implement it.

Thank you.

**Comment by ArturasRa** [comment]
You may use configuration file now, which should be located at $HOME/.cherry.yaml.

You may specify several profiles, for example:

```
user1:
  project-id: 68433
  team-id: 28519
  token: LCJpYXQiOjE1NjM1MjMyNzR9d2SJm6kNllkq
user2:
  project-id: 40283
  team-id: 28519
  token: iUCq4JxHYjXuaUG0b4VAr8gkvd2SJm6kNllk
default_profile: user1
```

Default profile of user1 will be used. If you want to switch to another profile, you need to issue command:

```
cherryctl profile set -p user2
```

All three variables (project-id, team-id and token) must be specified in config file in order to use it.

In such case you will not longer need to specify those variables in command line arguments.
